import {defineArrayMember, defineField, defineType} from 'sanity'
import {DocumentTextIcon} from '@sanity/icons/DocumentText'
import {seoFields} from './seoFields'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'صفحة من نحن',
  type: 'document',
  icon: DocumentTextIcon,
  groups: [
    {name: 'intro', title: 'المقدمة', default: true},
    {name: 'mission', title: 'الرسالة والرؤية'},
    {name: 'media', title: 'الصور'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'titleAr', title: 'عنوان الصفحة (عربي)', type: 'string', group: 'intro'}),
    defineField({name: 'titleEn', title: 'عنوان الصفحة (English)', type: 'string', group: 'intro'}),
    defineField({name: 'headingAr', title: 'العنوان الرئيسي (عربي)', type: 'string', group: 'intro'}),
    defineField({name: 'headingEn', title: 'العنوان الرئيسي (English)', type: 'string', group: 'intro'}),
    defineField({name: 'introAr', title: 'المقدمة (عربي)', type: 'text', rows: 4, group: 'intro'}),
    defineField({name: 'introEn', title: 'المقدمة (English)', type: 'text', rows: 4, group: 'intro'}),
    defineField({name: 'doctorLeadAr', title: 'نبذة الدكتور (عربي)', type: 'text', rows: 4, group: 'intro'}),
    defineField({name: 'doctorLeadEn', title: 'نبذة الدكتور (English)', type: 'text', rows: 4, group: 'intro'}),
    defineField({name: 'commitmentAr', title: 'الالتزام (عربي)', type: 'text', rows: 3, group: 'intro'}),
    defineField({name: 'commitmentEn', title: 'الالتزام (English)', type: 'text', rows: 3, group: 'intro'}),
    defineField({name: 'fullTextAr', title: 'النص الكامل HTML (عربي)', type: 'text', rows: 6, group: 'intro'}),
    defineField({name: 'fullTextEn', title: 'النص الكامل HTML (English)', type: 'text', rows: 6, group: 'intro'}),
    defineField({name: 'missionTitleAr', title: 'عنوان الرسالة (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'missionTitleEn', title: 'عنوان الرسالة (English)', type: 'string', group: 'mission'}),
    defineField({name: 'missionAr', title: 'الرسالة (عربي)', type: 'text', rows: 4, group: 'mission'}),
    defineField({name: 'missionEn', title: 'الرسالة (English)', type: 'text', rows: 4, group: 'mission'}),
    defineField({name: 'visionTitleAr', title: 'عنوان الرؤية (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'visionTitleEn', title: 'عنوان الرؤية (English)', type: 'string', group: 'mission'}),
    defineField({name: 'visionAr', title: 'الرؤية (عربي)', type: 'text', rows: 4, group: 'mission'}),
    defineField({name: 'visionEn', title: 'الرؤية (English)', type: 'text', rows: 4, group: 'mission'}),
    defineField({name: 'goalsTitleAr', title: 'عنوان الأهداف (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'goalsTitleEn', title: 'عنوان الأهداف (English)', type: 'string', group: 'mission'}),
    defineField({name: 'goalsAr', title: 'الأهداف (عربي)', type: 'array', group: 'mission', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'goalsEn', title: 'الأهداف (English)', type: 'array', group: 'mission', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'whyTitleAr', title: 'عنوان ما يميزنا (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'whyTitleEn', title: 'عنوان ما يميزنا (English)', type: 'string', group: 'mission'}),
    defineField({name: 'whyAr', title: 'ما يميزنا (عربي)', type: 'array', group: 'mission', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'whyEn', title: 'ما يميزنا (English)', type: 'array', group: 'mission', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'expertiseTitleAr', title: 'عنوان الخبرات (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'expertiseTitleEn', title: 'عنوان الخبرات (English)', type: 'string', group: 'mission'}),
    defineField({name: 'expertiseHeadingAr', title: 'عنوان فرعي للخبرات (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'expertiseHeadingEn', title: 'عنوان فرعي للخبرات (English)', type: 'string', group: 'mission'}),
    defineField({name: 'expertiseTextAr', title: 'نص الخبرات HTML (عربي)', type: 'text', rows: 4, group: 'mission'}),
    defineField({name: 'expertiseTextEn', title: 'نص الخبرات HTML (English)', type: 'text', rows: 4, group: 'mission'}),
    defineField({name: 'careAreasTitleAr', title: 'عنوان مجالات الرعاية (عربي)', type: 'string', group: 'mission'}),
    defineField({name: 'careAreasTitleEn', title: 'عنوان مجالات الرعاية (English)', type: 'string', group: 'mission'}),
    defineField({name: 'image', title: 'صورة الصفحة', type: 'image', options: {hotspot: true}, group: 'media'}),
    defineField({name: 'patternImage', title: 'صورة الخلفية', type: 'image', options: {hotspot: true}, group: 'media'}),
    ...seoFields.map((field) => ({...field, group: 'seo'})),
  ],
  preview: {select: {title: 'headingAr', media: 'image'}},
})
