import {defineField, defineType} from 'sanity'
import {CogIcon} from '@sanity/icons/Cog'
import {seoFields} from './seoFields'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'إعدادات الموقع',
  type: 'document',
  icon: CogIcon,
  groups: [
    {name: 'general', title: 'عام', default: true},
    {name: 'contact', title: 'تواصل'},
    {name: 'social', title: 'سوشيال'},
    {name: 'pages', title: 'عناوين الصفحات'},
    {name: 'home', title: 'الرئيسية'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'nameAr', title: 'اسم العيادة (عربي)', type: 'string', group: 'general', validation: (rule) => rule.required()}),
    defineField({name: 'nameEn', title: 'اسم العيادة (English)', type: 'string', group: 'general'}),
    defineField({name: 'shortNameAr', title: 'الاسم المختصر (عربي)', type: 'string', group: 'general'}),
    defineField({name: 'shortNameEn', title: 'الاسم المختصر (English)', type: 'string', group: 'general'}),
    defineField({name: 'taglineAr', title: 'النبذة (عربي)', type: 'string', group: 'general'}),
    defineField({name: 'taglineEn', title: 'النبذة (English)', type: 'string', group: 'general'}),
    defineField({name: 'url', title: 'رابط الموقع', type: 'url', group: 'general'}),
    defineField({name: 'logo', title: 'اللوجو', type: 'image', options: {hotspot: true}, group: 'general'}),
    defineField({name: 'doctorImage', title: 'صورة الدكتور', type: 'image', options: {hotspot: true}, group: 'general'}),
    defineField({name: 'aboutImage', title: 'صورة من نحن', type: 'image', options: {hotspot: true}, group: 'general'}),
    defineField({name: 'breadcrumbBg', title: 'خلفية البنر', type: 'image', options: {hotspot: true}, group: 'general'}),
    defineField({name: 'defaultOgImage', title: 'صورة المشاركة', type: 'image', options: {hotspot: true}, group: 'general'}),
    defineField({name: 'videoBanner', title: 'رابط فيديو الهيرو', type: 'string', group: 'general'}),
    defineField({name: 'copyrightAr', title: 'حقوق النشر (عربي)', type: 'string', group: 'general'}),
    defineField({name: 'copyrightEn', title: 'حقوق النشر (English)', type: 'string', group: 'general'}),

    defineField({name: 'phone', title: 'الهاتف', type: 'string', group: 'contact'}),
    defineField({name: 'phoneDisplay', title: 'عرض الهاتف', type: 'string', group: 'contact'}),
    defineField({name: 'phoneAlt', title: 'هاتف بديل', type: 'string', group: 'contact'}),
    defineField({name: 'phoneAltDisplay', title: 'عرض الهاتف البديل', type: 'string', group: 'contact'}),
    defineField({name: 'whatsapp', title: 'واتساب (بدون +)', type: 'string', group: 'contact'}),
    defineField({name: 'whatsappHref', title: 'رابط واتساب', type: 'url', group: 'contact'}),
    defineField({name: 'email', title: 'الإيميل الظاهر', type: 'string', group: 'contact'}),
    defineField({name: 'contactEmail', title: 'إيميل استلام الفورم', type: 'string', group: 'contact'}),
    defineField({name: 'addressAr', title: 'العنوان (عربي)', type: 'text', rows: 2, group: 'contact'}),
    defineField({name: 'addressEn', title: 'العنوان (English)', type: 'text', rows: 2, group: 'contact'}),
    defineField({name: 'hoursAr', title: 'مواعيد العمل (عربي)', type: 'string', group: 'contact'}),
    defineField({name: 'hoursEn', title: 'مواعيد العمل (English)', type: 'string', group: 'contact'}),
    defineField({name: 'mapEmbed', title: 'رابط خريطة Google', type: 'url', group: 'contact'}),
    defineField({
      name: 'geo',
      title: 'الإحداثيات',
      type: 'object',
      group: 'contact',
      fields: [
        defineField({name: 'latitude', title: 'Latitude', type: 'number'}),
        defineField({name: 'longitude', title: 'Longitude', type: 'number'}),
      ],
    }),
    defineField({name: 'contactTitleAr', title: 'عنوان صفحة التواصل (عربي)', type: 'string', group: 'contact'}),
    defineField({name: 'contactTitleEn', title: 'عنوان صفحة التواصل (English)', type: 'string', group: 'contact'}),
    defineField({name: 'formTitleAr', title: 'عنوان الفورم (عربي)', type: 'string', group: 'contact'}),
    defineField({name: 'formTitleEn', title: 'عنوان الفورم (English)', type: 'string', group: 'contact'}),
    defineField({name: 'formSuccessAr', title: 'رسالة النجاح (عربي)', type: 'string', group: 'contact'}),
    defineField({name: 'formSuccessEn', title: 'رسالة النجاح (English)', type: 'string', group: 'contact'}),

    defineField({
      name: 'social',
      title: 'السوشيال',
      type: 'object',
      group: 'social',
      fields: [
        defineField({name: 'facebook', title: 'Facebook', type: 'url'}),
        defineField({name: 'instagram', title: 'Instagram', type: 'url'}),
        defineField({name: 'youtube', title: 'YouTube', type: 'url'}),
        defineField({name: 'tiktok', title: 'TikTok', type: 'url'}),
        defineField({name: 'snapchat', title: 'Snapchat', type: 'url'}),
      ],
    }),

    defineField({name: 'galleryTitleAr', title: 'عنوان المعرض (عربي)', type: 'string', group: 'pages'}),
    defineField({name: 'galleryTitleEn', title: 'عنوان المعرض (English)', type: 'string', group: 'pages'}),
    defineField({name: 'gallerySubtitleAr', title: 'وصف المعرض (عربي)', type: 'string', group: 'pages'}),
    defineField({name: 'gallerySubtitleEn', title: 'وصف المعرض (English)', type: 'string', group: 'pages'}),
    defineField({name: 'videosTitleAr', title: 'عنوان الفيديوهات (عربي)', type: 'string', group: 'pages'}),
    defineField({name: 'videosTitleEn', title: 'عنوان الفيديوهات (English)', type: 'string', group: 'pages'}),
    defineField({name: 'videosSubtitleAr', title: 'وصف الفيديوهات (عربي)', type: 'string', group: 'pages'}),
    defineField({name: 'videosSubtitleEn', title: 'وصف الفيديوهات (English)', type: 'string', group: 'pages'}),
    defineField({name: 'testimonialsTitleAr', title: 'عنوان الآراء (عربي)', type: 'string', group: 'pages'}),
    defineField({name: 'testimonialsTitleEn', title: 'عنوان الآراء (English)', type: 'string', group: 'pages'}),
    defineField({name: 'testimonialsSubtitleAr', title: 'وصف الآراء (عربي)', type: 'string', group: 'pages'}),
    defineField({name: 'testimonialsSubtitleEn', title: 'وصف الآراء (English)', type: 'string', group: 'pages'}),

    defineField({
      name: 'homeSections',
      title: 'عناوين الرئيسية',
      type: 'object',
      group: 'home',
      fields: [
        defineField({name: 'aboutTagAr', title: 'وسم من نحن (عربي)', type: 'string'}),
        defineField({name: 'aboutTagEn', title: 'وسم من نحن (English)', type: 'string'}),
        defineField({name: 'servicesTagAr', title: 'وسم الخدمات (عربي)', type: 'string'}),
        defineField({name: 'servicesTagEn', title: 'وسم الخدمات (English)', type: 'string'}),
        defineField({name: 'servicesHeadingAr', title: 'عنوان الخدمات (عربي)', type: 'string'}),
        defineField({name: 'servicesHeadingEn', title: 'عنوان الخدمات (English)', type: 'string'}),
        defineField({name: 'casesTagAr', title: 'وسم المعرض (عربي)', type: 'string'}),
        defineField({name: 'casesTagEn', title: 'وسم المعرض (English)', type: 'string'}),
        defineField({name: 'casesHeadingAr', title: 'عنوان المعرض (عربي)', type: 'string'}),
        defineField({name: 'casesHeadingEn', title: 'عنوان المعرض (English)', type: 'string'}),
        defineField({name: 'reviewsTagAr', title: 'وسم الآراء (عربي)', type: 'string'}),
        defineField({name: 'reviewsTagEn', title: 'وسم الآراء (English)', type: 'string'}),
        defineField({name: 'reviewsHeadingAr', title: 'عنوان الآراء (عربي)', type: 'string'}),
        defineField({name: 'reviewsHeadingEn', title: 'عنوان الآراء (English)', type: 'string'}),
        defineField({name: 'reviewsSideTagAr', title: 'وسم جانب الآراء (عربي)', type: 'string'}),
        defineField({name: 'reviewsSideTagEn', title: 'وسم جانب الآراء (English)', type: 'string'}),
        defineField({name: 'reviewsSideHeadingAr', title: 'عنوان جانب الآراء (عربي)', type: 'string'}),
        defineField({name: 'reviewsSideHeadingEn', title: 'عنوان جانب الآراء (English)', type: 'string'}),
        defineField({name: 'reviewsSideTextAr', title: 'نص جانب الآراء (عربي)', type: 'text', rows: 3}),
        defineField({name: 'reviewsSideTextEn', title: 'نص جانب الآراء (English)', type: 'text', rows: 3}),
        defineField({name: 'blogTagAr', title: 'وسم المقالات (عربي)', type: 'string'}),
        defineField({name: 'blogTagEn', title: 'وسم المقالات (English)', type: 'string'}),
        defineField({name: 'blogHeadingAr', title: 'عنوان المقالات (عربي)', type: 'string'}),
        defineField({name: 'blogHeadingEn', title: 'عنوان المقالات (English)', type: 'string'}),
      ],
    }),
    ...seoFields.map((field) => ({...field, group: 'seo'})),
  ],
  preview: {select: {title: 'nameAr', media: 'logo'}},
})
